### ISSUE TITLE
Is this repo actively maintained??

### ISSUE THREAD

**Issue by umair2288** [citusdata/django-multitenant#103]
I'm looking into using this library for one of my projects. I just wanted to know if this library is maintained or not.

**Comment by grucha** [comment]
I'm in the same spot ;-)

**Comment by rob101** [comment]
@louiseGrandjonc what are your plans for the repo?

**Comment by louiseGrandjonc** [comment]
Hi,

As I’m not an employee of citus/Microsoft anymore, I don’t have push access. So I think the question would be more for the citus team at Microsoft.

Louise

**Comment by HaidarZ** [comment]
+1

**Comment by s4ke** [comment]
@JelteF ping :)

**Comment by JelteF** [comment]
FYI I released django-multitenant 2.4.0 yesterday

**Comment by HaidarZ** [comment]
> FYI I released django-multitenant 2.4.0 yesterday

You forgot to release it as a Github release. We're used to be notified for new releases if we're watching a repo.

**Comment by JelteF** [comment]
I created a Github release now too.
